### ISSUE TITLE
Feature - Page of create register  

### ISSUE THREAD

**Issue by AbejaCruz** [platzily/platzily-admin#37]
creation of the page to register a new user in the admin platform

## Checklist ✅

- [x ] The issue is present in the latest release.
- [ ] I have searched the issues of this repository and believe that this is not a duplicate.

## Summary 💡
creation that allows the registration of users according to the designs in figma

## Motivation 🔦

allow users to create their profile in order to access all the services offered by the admin platform

**Comment by zago-code** [comment]
The register is managed from Auth0
